--- #YAML:1.0
name:               Locale-SubCountry
version:            1.57
abstract:           Convert state, province, county etc. names to/from ISO 3166-2 codes
author:
    - Kim Ryan <kimryan at cpan org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    locale:               1
    strict:               1.04
    Test::More:           0.94
    Test::Pod:            1.44
    Test::Pod::Coverage:  1.04
    utf8:                 1.09
    warnings:             1.12
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
