---
abstract: 'Convert state, province, county etc. names to/from ISO 3166-2 codes'
author:
  - 'Kim Ryan <kimryan at cpan org>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.04
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-SubCountry
provides:
  Locale::SubCountry:
    file: lib/Locale/SubCountry.pm
    version: 1.61
  Locale::SubCountry::Data:
    file: lib/Locale/SubCountry/Data.pm
    version: 1.61
  Locale::SubCountry::World:
    file: lib/Locale/SubCountry.pm
    version: 1.61
requires:
  Test::Pod::Coverage: 1.04
  locale: 1
  strict: 1.04
  utf8: 1.09
  warnings: 1.12
resources:
  license: http://dev.perl.org/licenses/
version: 1.61
