--- #YAML:1.0
name:                Locale-SubCountry
version:             1.43
abstract:            convert state, province, county ... names to/from ISO 3166-2 code
license:             perl
author:              
    - Kim Ryan <kimryan at cpan org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
